rpmsg: core: Fix compilation warnings
../drivers/rpmsg/rpmsg_core.c:378:33: error: passing 'char **' to parameter of type 'const char **' discards qualifiers in nested pointer types [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
        ret = driver_set_override(dev, &rpdev->driver_override, buf, count);
                                       ^~~~~~~~~~~~~~~~~~~~~~~
../include/linux/device/driver.h:158:58: note: passing argument to parameter 'override' here
int driver_set_override(struct device *dev, const char **override,
                                                         ^

(cherry picked from commit d711626a80a9ecdac6e6a9f626cff7db109cd66a)