drivers: gpu: mali-valhall: fix function prototype warning
../drivers/gpu/mediatek/gpu_mali/mali_valhall/mali-r32p1/drivers/gpu/arm/midgard/platform/mtk_platform_common/mtk_mfg_counter.c:772:23: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int gator_gpu_pmu_init()
                      ^
                       void

Change-Id: Ie9feea8443abb3c3a5ca6ad9402fe3343ef3fdb0
Signed-off-by: CloudedQuartz <ayan.pande06@gmail.com>
(cherry picked from commit 15963c39be155e62ef3561c73a637016b6963901)